CREATE TABLE "ANALIS" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AN_APP_NO" nvarchar(7),
  "AN_DESC_NO" nvarchar(9),
  "AN_SER_NO" nvarchar(2)
);

CREATE TABLE "ARRAYS" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" nvarchar(20),
  "AR_LEVEL" nvarchar(1)
);

CREATE TABLE "ARRAYS1" (
  "ar_typ" nvarchar(2),
  "ar_no" float,
  "ar_desc" nvarchar(30)
);

CREATE TABLE "ARTICLE" (
  "ART_APP_NO" nvarchar(7) PRIMARY KEY,
  "ART_YEAR" float,
  "ART_VOL" float,
  "ART_NO" int,
  "ART_DTE" datetime,
  "ART_PER_NO" float,
  "ART_SUB_TY" nvarchar(2),
  "ART_PG_NO" nvarchar(5),
  "ART_CO_NO" nvarchar(3),
  "ART_SER_NO" float,
  "ART_FLM_NO" float,
  "ART_TYP" float,
  "ART_LANG" nvarchar(1),
  "ART_DTE1" datetime,
  "ART_PER1" float,
  "ART_CHOICE" float,
  "art_upd" float,
  "ART_PIC" char(6),
  "ART_LANG1" char(2)
);

CREATE TABLE "AUTHER" (
  "AUT_TYP" nvarchar(2),
  "AUT_NO" float,
  "AUT_NAM" nvarchar(100),
  "aut_sub_no" char(10)
);

CREATE TABLE "BOOK" (
  "BK_APP_NO" nvarchar(7),
  "BK_PUB_LOC" nvarchar(8),
  "BK_PBLSHR" float,
  "BK_PUB_TYP" nvarchar(2),
  "BK_SLCT_NO" nvarchar(20),
  "BK_PUB_DTE" datetime,
  "BK_MAT_CNT" nvarchar(10),
  "BK_LANG3" nvarchar(1),
  "BK_EDTN" float,
  "BK_RDMK" nvarchar(15),
  "BK_CVR" nvarchar(2),
  "BK_PG_NO" float,
  "BK_PRT_NO" float,
  "BK_IS_SER" bit NOT NULL,
  "BK_NO_CP" float,
  "BK_REG_NO" float,
  "BK_ADT_TTL" nvarchar(75),
  "BK_KHALIF" nvarchar(35),
  "BK_VOL" float,
  "BK_WATH_TY" nvarchar(2),
  "BK_QUATER" nvarchar(11),
  "BK_SAVE" float,
  "BK_PRIX" float,
  "BK_IKTDTE" datetime,
  "BK_MTRJM" float,
  "BK_SER_TTL" nvarchar(60),
  "BK_SER_NO" float,
  "BK_LANG1" nvarchar(1),
  "bk_vol1" float,
  "bk_mjld" float,
  "bk_mjld1" float,
  "bk_jz" float,
  "bk_jz1" float,
  "bk_content" varchar(130),
  "bk_memo" nvarchar(200),
  "bk_year_pub" float,
  "bk_typ_year" float,
  "bk_result" nvarchar(1000),
  "bk_free" float,
  "bk_lang" nvarchar(1),
  "bk_iar_no" nvarchar(6),
  "bk_stat" char(2)
);

CREATE TABLE "CHARIT" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CHA_NO" nvarchar(6),
  "CHA_SUB" nvarchar(2),
  "CHA_TYP" float,
  "CHA_TIME" float,
  "CHA_DTE" datetime,
  "CHA_NUM" float,
  "CHA_TYP1" float,
  "CHA_SOURCE" nvarchar(3),
  "CHA_DTE1" datetime,
  "CHA_TITLE" nvarchar(70),
  "CHA_STOCK" float,
  "CHA_NBDIS" float,
  "CHA_SUBJCT" nvarchar(3),
  "CHA_FRM" nvarchar(3),
  "cha_to" nvarchar(3),
  "cha_prsfrm" nvarchar(3),
  "cha_prsto" nvarchar(3),
  "cha_opr_no" nvarchar(7),
  "cha_tmcode" nvarchar(2)
);

CREATE TABLE "CODING" (
  "SUB_LEVE" nvarchar(1),
  "SUB_CODE" nvarchar(4),
  "SUB_DESC" nvarchar(100)
);

CREATE TABLE "COTE_PUB" (
  "CTP_NO" float,
  "CTP_NAM" nvarchar(40)
);

CREATE TABLE "DICT" (
  "SUB_CODE3" nvarchar(9),
  "NUM" float,
  "SUB_DESC3" nvarchar(30)
);

CREATE TABLE "DIGIT" (
  "DIG_NO" char(7) NOT NULL,
  "DIG_DIG_NO" char(6),
  "DIG_TYP" char(4),
  "DIG_SER" int NOT NULL,
  "DIG_TYP1" char(2),
  "DIG_O" int,
  "DIG_M" int,
  "DIG_S" int,
  "DIG_O1" int,
  "DIG_M1" int,
  "DIG_S1" int,
  "DIG_SIZE" decimal(5,2),
  "DIG_NOCHRT" char(6),
  "dig_newnochrt" char(6),
  "dig_typchrt" char(2),
  "dig_geochrt" char(10),
  "dig_choice" int,
  "dig_nochrt1" char(8),
  "dig_typmat" char(2),
  "dig_typ_high" char(3),
  PRIMARY KEY ("DIG_NO", "DIG_SER")
);

CREATE TABLE "FILE_ADD" (
  "FAD_APP_NO" nvarchar(7),
  "FAD_DESC_N" nvarchar(9),
  "FAD_SER_NO" nvarchar(2),
  "FAD_FAD_T1" nvarchar(1),
  "FAD_FAD_T2" nvarchar(1),
  "FAD_RLTV_N" nvarchar(2),
  "FAD_FAD_NO" nvarchar(10)
);

CREATE TABLE "FILE_ADD2" (
  "FAD_APP_NO" nvarchar(7),
  "FAD_DESC_N" nvarchar(9),
  "FAD_SER_NO" nvarchar(2),
  "FAD_FAD_T1" nvarchar(1),
  "FAD_FAD_T2" nvarchar(1),
  "FAD_RLTV_N" nvarchar(2),
  "FAD_FAD_NO" nvarchar(10)
);

CREATE TABLE "GEO" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "GEO_APP_NO" nvarchar(7),
  "GEO_DESC_N" nvarchar(9),
  "GEO_SER_NO" nvarchar(2),
  "GEO_GEO_NO" nvarchar(10)
);

CREATE TABLE "ISTARA" (
  "IAR_NO" nvarchar(6) NOT NULL,
  "IAR_DTE" datetime,
  "IAR_PRS" nvarchar(5),
  "IAR_TYP" float,
  "IAR_CAUSE" nvarchar(2),
  "IAR_PERIOD" float,
  "IAR_DTE1" datetime,
  "IAR_DTE2" datetime,
  "IAR_RMK" nvarchar(70),
  "IAR_TYP1" float,
  "iar_book" nvarchar(7),
  "iar_serial" float NOT NULL,
  "iar_ent" nvarchar(3),
  "iar_ist_typ" float NOT NULL,
  "iar_reg_no" float,
  "iar_tamin" float,
  PRIMARY KEY ("IAR_NO", "iar_serial", "iar_ist_typ")
);

CREATE TABLE "IST_BK" (
  "IAB_NO" nvarchar(5),
  "IAB_SER" float,
  "IAB_BOOK" nvarchar(7)
);

CREATE TABLE "IST_OTH" (
  "IAO_NO" nvarchar(5),
  "IAO_SER" float,
  "IAO_TIT" nvarchar(60),
  "IAO_TYP" float,
  "IAO_NB" float
);

CREATE TABLE "MACNZ" (
  "SUB_CODE" nvarchar(9),
  "SUB_LEVEL" nvarchar(1),
  "SUB_DESC" nvarchar(40),
  "SUB_LOGIC" float
);

CREATE TABLE "MEM" (
  "SUB_CODE4" nvarchar(9),
  "NUMBER" float,
  "SUB_DESC4" nvarchar(30)
);

CREATE TABLE "NAROWER" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NAR_APP_NO" nvarchar(7),
  "NAR_DESC_N" nvarchar(9),
  "NAR_SER_NO" nvarchar(2),
  "NAR_RLTV_N" nvarchar(2),
  "NAR_NAR_TY" nvarchar(1),
  "NAR_NAR_NO" nvarchar(9)
);

CREATE TABLE "NEWS" (
  "NEWS_NO" nvarchar(7),
  "NEWS_DOC" nvarchar(2),
  "NEWS_DTE_D" datetime,
  "NEWS_DTE" datetime,
  "NEWS_NUM" float,
  "NEWS_TIT1" nvarchar(75),
  "NEWS_TIT2" nvarchar(75),
  "NEWS_DES_T" nvarchar(2),
  "NEWS_DES_D" datetime,
  "NEWS_DES_P" float,
  "NEWS_PUB" float,
  "NEWS_DES_N" nvarchar(9),
  "NEWS_MLH" float
);

CREATE TABLE "NEWS_WRD" (
  "WRD_APP_NO" nvarchar(7),
  "WRD_WORD" nvarchar(12)
);

CREATE TABLE "OPR_CHRT" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OPR_NO" nvarchar(7),
  "OPR_SER" float,
  "OPR_NO1" nvarchar(6),
  "OPR_SUB" nvarchar(2),
  "OPR_DTE" datetime,
  "OPR_TIME" nvarchar(15),
  "OPR_COTFRM" nvarchar(3),
  "OPR_PRSFRM" nvarchar(3),
  "OPR_COTTO" nvarchar(3),
  "OPR_PRSTO" nvarchar(3),
  "OPR_DTE1" datetime,
  "OPR_RMK" nvarchar(50),
  "OPR_TITLE" nvarchar(70),
  "OPR_TRANS" bit NOT NULL,
  "opr_choice" char(20),
  "opr_extcote" char(10)
);

CREATE TABLE "PERIOD" (
  "PER_PER_NO" float,
  "PER_PER_NA" nvarchar(40),
  "PER_PUB_LO" float,
  "PER_ST_DTE" datetime,
  "PER_LANG" nvarchar(1),
  "PER_RDMD" nvarchar(15),
  "PER_TYP" float,
  "PER_GEO" nvarchar(10),
  "PER_TYP1" nvarchar(2),
  "PER_FREQ" nvarchar(2),
  "PER_ADRS" nvarchar(65),
  "PER_TEL" nvarchar(16),
  "PER_AMNT" float,
  "PER_PRIX" float,
  "PER_PBLSHR" float,
  "PER_PRIX1" float,
  "PER_PUB" nvarchar(10),
  "PER_MOASS" nvarchar(10),
  "PER_TAHRIR" nvarchar(10),
  "PER_DIRCT" nvarchar(10),
  "PER_PRESD" nvarchar(10),
  "PER_UTILS" float,
  "PER_GEO1" nvarchar(10),
  "PER_TAH1" nvarchar(10),
  "PER_FAX" nvarchar(15),
  "PER_CREAT" nvarchar(10),
  "PER_DTE" datetime,
  "per_email" nvarchar(60),
  "per_website" nvarchar(60)
);

CREATE TABLE "PERSON" (
  "PRS_NO" char(10),
  "PRS_NAME" nvarchar(50),
  "PRS_INST" nvarchar(10),
  "PRS_ADRS" nvarchar(100),
  "prs_inst_tel" nvarchar(30),
  "PRS_INST_BOX" nvarchar(15),
  "PRS_INST_DIRCT" nvarchar(50),
  "PRS_INST_EMAIL" nvarchar(50),
  "PRS_KAYD" nvarchar(10),
  "PRS_BRTH_DTE" datetime,
  "PRS_VLG" nvarchar(10),
  "PRS_SAKAN" nvarchar(10),
  "PRS_ADRS1" nvarchar(100),
  "PRS_TEL" nvarchar(50),
  "PRS_EMAIL" nvarchar(50),
  "PRS_BOX" nvarchar(50),
  "prs_qualty" nvarchar(3),
  "prs_icht_dte1" datetime,
  "prs_ent" char(2),
  "prs_mzhb" char(3),
  "prs_politc" char(3),
  "prs_social_media" char(100),
  "prs_oldjob" char(3),
  "prs_sex" char(3)
);

CREATE TABLE "PERSON1" (
  "PRS_NO" nvarchar(5),
  "PRS_NAME" nvarchar(25),
  "PRS_INST" nvarchar(10),
  "PRS_ADRS" nvarchar(40),
  "prs_inst_tel" nvarchar(30),
  "PRS_INST_BOX" nvarchar(15),
  "PRS_INST_DIRCT" nvarchar(10),
  "PRS_INST_EMAIL" nvarchar(30),
  "PRS_KAYD" nvarchar(10),
  "PRS_BRTH_DTE" datetime,
  "PRS_VLG" nvarchar(10),
  "PRS_SAKAN" nvarchar(10),
  "PRS_ADRS1" nvarchar(50),
  "PRS_TEL" nvarchar(20),
  "PRS_EMAIL" nvarchar(30),
  "PRS_BOX" nvarchar(15),
  "PRS_TYP_ICHT" int,
  "prs_qualty" nvarchar(4),
  "prs_icht_dte1" datetime,
  "prs_icht_dte2" datetime,
  "prs_ent" char(2)
);

CREATE TABLE "PICTURE" (
  "pic_no" nvarchar(7),
  "pic_ng_no" nvarchar(6),
  "pic_pos_no" nvarchar(6),
  "pic_doc" nvarchar(3),
  "pic_doc_dte" datetime,
  "pic_ent" nvarchar(3),
  "pic_ent_dte" datetime,
  "pic_prs" nvarchar(3),
  "pic_dte" datetime,
  "pic_tit" nvarchar(100),
  "pic_cot" nvarchar(10),
  "pic_geo" nvarchar(10),
  "pic_typ" float,
  "pic_form" float,
  "pic_len" float,
  "pic_large" float,
  "pic_qualty" float,
  "pic_sub" float,
  "pic_rmrk" nvarchar(70),
  "pic_copy" float,
  "pic_lbn" nvarchar(5),
  "pic_page" nvarchar(5),
  "pic_line" nvarchar(5),
  "pic_typ1" float,
  "pic_brind" float,
  "pic_choice" float
);

CREATE TABLE "POSITION" (
  "POS_NO" nvarchar(10),
  "POS_NAM" nvarchar(80),
  "DAT_REC" datetime
);

CREATE TABLE "POUT" (
  "auto" int PRIMARY KEY,
  "OUT_IST" nvarchar(2),
  "OUT_NUM" float,
  "OUT_DESC" nvarchar(25),
  "OUT_NAME" nvarchar(20),
  "OUT_FIELD" nvarchar(20),
  "OUT_SCOND0" nvarchar(70),
  "OUT_SCOND" nvarchar(70),
  "OUT_SCOND1" nvarchar(120),
  "OUT_MCOND" nvarchar(45),
  "OUT_MCOND1" nvarchar(45),
  "out_ext" nvarchar(5),
  "OUT_LEN" float,
  "OUT_LEN1" float,
  "OUT_COND" nvarchar(80),
  "OUT_SELECT" nvarchar(20),
  "OUT_INDX" float,
  "OUT_INDX3" float,
  "OUT_SEK" nvarchar(1),
  "OUT_IF" nvarchar(1),
  "OUT_CHIOCE" float,
  "OUT_NATURE" nvarchar(1),
  "OUT_SLCT1" nvarchar(20),
  "OUT_INDX1" nvarchar(20),
  "OUT_COD" nvarchar(60),
  "OUT_VCOD" nvarchar(2),
  "OUT_NAMCOD" nvarchar(35),
  "OUT_NAMCOD1" nvarchar(12),
  "OUT_FINDX" nvarchar(1),
  "OUT_RCRN" nvarchar(1),
  "OUT_INDX12" float,
  "OUT_COND1" nvarchar(40),
  "OUT_TYP" nvarchar(1),
  "OUT_REL" nvarchar(20),
  "OUT_CHIO1" float,
  "out_rel1" nvarchar(12),
  "out_rel2" nvarchar(12),
  "out_rel3" nvarchar(12)
);

CREATE TABLE "POUT1" (
  "OUT_IST" nvarchar(2),
  "OUT_NUM" float,
  "OUT_DESC" nvarchar(25),
  "OUT_NAME" nvarchar(12),
  "OUT_FIELD" nvarchar(100),
  "OUT_SCOND0" nvarchar(100),
  "OUT_SCOND" nvarchar(200),
  "OUT_SCOND1" nvarchar(200),
  "OUT_MCOND" nvarchar(100),
  "OUT_MCOND1" nvarchar(100),
  "OUT_LEN" float,
  "OUT_LEN1" float,
  "OUT_COND" nvarchar(40),
  "OUT_SELECT" nvarchar(53),
  "OUT_INDX" float,
  "OUT_INDX3" float,
  "OUT_SEK" nvarchar(1),
  "OUT_IF" nvarchar(1),
  "OUT_CHIOCE" float,
  "OUT_NATURE" nvarchar(1),
  "OUT_SLCT1" nvarchar(53),
  "OUT_INDX1" nvarchar(53),
  "OUT_COD" nvarchar(80),
  "OUT_VCOD" nvarchar(2),
  "OUT_NAMCOD" nvarchar(50),
  "OUT_NAMCOD1" nvarchar(50),
  "OUT_RCRN" nvarchar(1),
  "OUT_INDX12" float,
  "OUT_COND1" nvarchar(50),
  "OUT_TYP" nvarchar(1),
  "OUT_REL" nvarchar(20),
  "OUT_CHIO1" float,
  "out_serial" float,
  "OUT_REL1" nvarchar(12),
  "OUT_REL2" nvarchar(12),
  "OUT_REL3" nvarchar(12)
);

CREATE TABLE "RELATIVE" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "REL_APP_NO" nvarchar(7),
  "REL_DESC_N" nvarchar(9),
  "REL_SER_NO" nvarchar(2),
  "REL_RLTV_N" nvarchar(2),
  "REL_RLTV_T" nvarchar(1),
  "REL_REL_NO" nvarchar(9)
);

CREATE TABLE "RELIS" (
  "SUB_CODE1" nvarchar(9),
  "SUB_CODE2" nvarchar(9),
  "RELITION" float
);

CREATE TABLE "REL_FORM" (
  "RLF_FORM1" nvarchar(10),
  "RLF_FORM2" nvarchar(10),
  "RLF_DTE" datetime,
  "RLF_DTE1" datetime,
  "RLF_REL" nvarchar(2)
);

CREATE TABLE "RES" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RES_APP_NO" nvarchar(7),
  "RES_APP_TY" nvarchar(2),
  "RES_RES_NO" float
);

CREATE TABLE "SERIES" (
  "SER_APP_NO" nvarchar(7),
  "SER_AC_TTL" nvarchar(40),
  "SER_AD_TTL" nvarchar(40),
  "SER_ACT_NO" float,
  "SER_ADD_NO" float
);

CREATE TABLE "SUBJECT" (
  "SUB_FORM" nvarchar(10),
  "SUB_MCNZ" nvarchar(9),
  "SUB_DTE" datetime,
  "SUB_DTE1" datetime,
  "SUB_REL" nvarchar(2)
);

CREATE TABLE "TEMP" (
  "FIELD_NAME" nvarchar(10),
  "FIELD_TYPE" nvarchar(1),
  "FIELD_LEN" float,
  "FIELD_DEC" float
);

CREATE TABLE "TEXT" (
  "TXT_APP_NO" nvarchar(7),
  "TXT_MEM" nvarchar(70),
  "txt_ser" float,
  "txt_page" float
);

CREATE TABLE "TIME" (
  "TM_APP_NO" nvarchar(7),
  "TM_DESC_NO" nvarchar(9),
  "TM_SER_NO" nvarchar(2),
  "TM_RLTV_NO" nvarchar(2),
  "TM_O" float,
  "TM_M" float,
  "TM_S" float,
  "TM_O1" float,
  "TM_M1" float,
  "TM_S1" float
);

CREATE TABLE "TRANS" (
  "TRS_OPNO" float,
  "TRS_NO" float,
  "TRS_DTE" datetime,
  "TRS_NUM" nvarchar(5),
  "TRS_NB" float,
  "TRS_YEAR" float,
  "TRS_TYP" float,
  "TRS_DTE1" datetime
);

CREATE TABLE "WORD" (
  "SUB_CODE6" nvarchar(10),
  "SUB_DESC6" nvarchar(12),
  "SUB_TYP6" nvarchar(1)
);

CREATE TABLE "abb" (
  "REL_APP_NO" nvarchar(7),
  "REL_DESC_N" nvarchar(9),
  "REL_SER_NO" nvarchar(2),
  "REL_RLTV_N" nvarchar(2),
  "REL_RLTV_T" nvarchar(1),
  "REL_REL_NO" nvarchar(9)
);

CREATE TABLE "abbas" (
  "id1" decimal(18,0)
);

CREATE TABLE "bnkout" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OUT_NUM" float,
  "OUT_DESC" nvarchar(40),
  "OUT_NAME" nvarchar(20),
  "OUT_FIELD" nvarchar(20),
  "OUT_SCOND0" nvarchar(70),
  "OUT_SCOND" nvarchar(70),
  "OUT_SCOND1" nvarchar(160),
  "OUT_MCOND" nvarchar(45),
  "OUT_MCOND1" nvarchar(30),
  "out_ext" nvarchar(5),
  "OUT_LEN" float,
  "OUT_LEN1" float,
  "OUT_COND" nvarchar(60),
  "OUT_DISPLAY" nvarchar(80),
  "OUT_SELECT" nvarchar(15),
  "out_fldselect" nvarchar(20),
  "OUT_INDX" nvarchar(15),
  "OUT_INDX3" nvarchar(15),
  "OUT_SEK" nvarchar(1),
  "OUT_IF" nvarchar(1),
  "OUT_CHIOCE" float,
  "OUT_NATURE" nvarchar(1),
  "OUT_SLCT1" nvarchar(15),
  "OUT_INDX1" nvarchar(15),
  "OUT_COD" nvarchar(60),
  "OUT_VCOD" nvarchar(2),
  "OUT_NAMCOD" nvarchar(35),
  "OUT_namcod1" nvarchar(15),
  "OUT_RCRN" nvarchar(1),
  "OUT_INDX12" float,
  "OUT_COND1" nvarchar(35),
  "OUT_TYP" nvarchar(1),
  "OUT_REL" nvarchar(12),
  "OUT_REL1" nvarchar(12),
  "OUT_REL2" nvarchar(12),
  "OUT_REL3" nvarchar(30),
  "OUT_T2" nvarchar(30),
  "OUT_CHIO1" float,
  "OUT_SCOND2" nvarchar(40),
  "OUT_MCOND2" nvarchar(40),
  "OUT_FIELD2" nvarchar(25),
  "OUT_SLCT2" float,
  "OUT_INDX2" float,
  "OUT_CAT" char(2)
);

CREATE TABLE "catogorie" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cat_no" char(2),
  "cat_num" int
);

CREATE TABLE "config" (
  "user_no" char(3),
  "user_name" char(50),
  "user_password" char(15),
  "user_cnf_path" char(100),
  "user_start" int,
  "USER_PWD" int,
  "user_cmpvd" char(100),
  "user_video_path" char(100),
  "user_company" int,
  "user_video_path1" char(100),
  "SITE_WLY" int,
  "user_level" char(1),
  "user_permition" int,
  "user_ent" char(2),
  "user_doc" char(2)
);

CREATE TABLE "date_subject" (
  "dte_app_no" char(7),
  "dte_ser_no" char(2),
  "dte_rel_no" char(2),
  "dte_desc_no" char(9),
  "dte_dte_deb" datetime,
  "dte_dte_fin" datetime
);

CREATE TABLE "demand" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dmd_no" char(7) NOT NULL,
  "dmd_ser" int NOT NULL,
  "dmd_user" char(3),
  "dmd_dte" datetime,
  "dmd_in" decimal(18,0),
  "dmd_out" decimal(18,9),
  "dmd_path" char(100),
  "dmd_time" decimal(18,0),
  "dmd_mch_no" char(7),
  "dmd_desc" char(100),
  "dmd_chek" int,
  "dmd_mch_stock" char(6),
  "dmd_s" int,
  "dmd_m" int,
  "dmd_o" int,
  "dmd_f" int,
  "dmd_cote" char(50),
  "dmd_time1" char(12),
  "dmd_chek1" bit
);

CREATE TABLE "form" (
  "SUB_TYP" nvarchar(2),
  "SUB_NO" nvarchar(8),
  "SUB_NAME" nvarchar(60),
  "SUB_DTE" datetime,
  "SUB_USER" char(3),
  "SUB_SEC" int,
  "SUB_NOJIHAD" int,
  "SUB_NAME_PRINT" char(100)
);

CREATE TABLE "form1" (
  "SUB_TYP" nvarchar(2),
  "SUB_NO" nvarchar(8),
  "SUB_NAME" nvarchar(80),
  "sub_dte" datetime
);

CREATE TABLE "main" (
  "MN_APP_NO" char(7) PRIMARY KEY,
  "m_no1" nvarchar(7),
  "MN_ACT_TTL" nvarchar(125),
  "MN_ACT" nvarchar(50),
  "MN_ADD_TTL" nvarchar(125),
  "MN_ADD" nvarchar(50),
  "MN_DATA_EN" nvarchar(2),
  "MN_APP_DOC" nvarchar(2),
  "MN_ENT_DTE" datetime,
  "MN_WRT_DTE" datetime,
  "MN_APP_REV" nvarchar(2),
  "mn_no" char(10),
  "MN_RESULT" char(1000),
  "MN_TYP" char(1),
  "mn_trans" int DEFAULT 0
);

CREATE TABLE "main2" (
  "MN_APP_NO" nvarchar(7),
  "MN_ACT_TTL" nvarchar(125),
  "MN_ACT" nvarchar(50),
  "MN_ADD_TTL" nvarchar(125),
  "MN_ADD" nvarchar(50),
  "MN_DATA_EN" nvarchar(2),
  "MN_APP_DOC" nvarchar(2),
  "MN_ENT_DTE" datetime,
  "MN_WRT_DTE" datetime,
  "MN_APP_REV" nvarchar(2),
  "MN_CHRT_NO" char(6),
  "MN_O" int,
  "MN_M" int,
  "MN_S" int,
  "MN_O1" int,
  "MN_M1" int,
  "MN_S1" int,
  "MN_SIZE" decimal(5,2),
  "MN_TYP" char(1),
  "MN_PIC" char(2),
  "MN_VOI" char(2),
  "MN_RESULT" nvarchar(500)
);

CREATE TABLE "posts" (
  "post_serial" char(6) PRIMARY KEY,
  "post_no" char(10),
  "post_sit_no" char(13),
  "post_doc_no" char(7),
  "post_deb_dte" datetime,
  "post_fin_dte" datetime,
  "post_wly_no" int,
  "post_stat" int,
  "post_level_no" char(2),
  "post_typ" int,
  "post_user" char(3),
  "post_permition" int,
  "post_level" char(1)
);

CREATE TABLE "ranjpath" (
  "rjp_no" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rjp_nofrom" char(10),
  "rjp_noto" char(10),
  "rjp_path" char(200),
  "rjp_typ" int
);

CREATE TABLE "result" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "res_no" char(7) NOT NULL,
  "res_ser" int NOT NULL,
  "res_dig_no" char(6),
  "res_typ" char(3),
  "res_typ1" char(2),
  "res_dte" datetime,
  "res_user_no" char(3),
  "res_no_ist" char(7),
  "res_prs" char(50),
  "res_cote" char(3),
  "res_permit" char(2),
  "res_subject" char(50)
);

CREATE TABLE "sites" (
  "sit_no" char(10),
  "sit_nolevel" char(13),
  "sit_level" char(2),
  "sit_proccess" char(10),
  "sit_desc" nvarchar(100),
  "sit_doc_no" char(7),
  "sit_deb_dte" datetime,
  "sit_fin_dte" datetime,
  "sit_free" int,
  "sit_typ" char(2),
  "sit_intkb" int,
  "sit_morch" int,
  "sit_wly_no" int,
  "sit_stat" char(2),
  "sit_user" char(3),
  "sit_permition" int,
  "sit_leve" char(1),
  "sit_kind" char(2),
  "sit_close_no" char(7)
);

CREATE TABLE "t_operation" (
  "F_DESC" nvarchar(4)
);

CREATE TABLE "text1" (
  "txt_no" nvarchar(7),
  "txt_desc_n" nvarchar(9),
  "txt_ser_no" nvarchar(2),
  "txt_rltv_n" nvarchar(2),
  "txt_rltv_typ" nvarchar(1),
  "txt_text" nvarchar(4000),
  "txt_nbpage" int
);

CREATE TABLE "tmp_fileadd" (
  "tmp_fad_no" nvarchar(7) NOT NULL,
  "tmp_ser" float,
  "tmp_file_name" nvarchar(50),
  "tmp_rmrk" nvarchar(50),
  "tmp_mk" nvarchar(30),
  "tmp_date" datetime,
  "tmp_user_no" char(3),
  "tmp_final" int
);

CREATE TABLE "user_bnkout" (
  "user_ist_no" char(2) NOT NULL,
  "user_no" char(3) NOT NULL,
  "user_out_num" int NOT NULL,
  "user_out_choice" int,
  "user_index" char(3),
  "user_sing" char(1),
  "user_out_choi1" int,
  "user_sing1" char(1),
  PRIMARY KEY ("user_ist_no", "user_no", "user_out_num")
);

CREATE TABLE "view_array01" (
  "ar_typ" nvarchar(2),
  "ar_no" float,
  "ar_desc" nvarchar(30)
);

CREATE TABLE "view_array03" (
  "auto" int NOT NULL,
  "ar_typ" nvarchar(2),
  "ar_no" float,
  "ar_desc" nvarchar(30)
);

CREATE TABLE "view_array04" (
  "auto" int NOT NULL,
  "ar_typ" nvarchar(2),
  "ar_no" float,
  "ar_desc" nvarchar(30)
);

CREATE TABLE "view_array1" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" nvarchar(20),
  "AR_LEVEL" nvarchar(1)
);

CREATE TABLE "view_array2" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" nvarchar(20),
  "AR_LEVEL" nvarchar(1)
);

CREATE TABLE "view_arrays" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" nvarchar(20),
  "AR_LEVEL" nvarchar(1)
);

CREATE TABLE "view_posts" (
  "post_no" char(10),
  "post_name" nvarchar(60),
  "post_doc_no" char(7),
  "post_deb_dte" datetime,
  "post_fin_dte" datetime,
  "post_wly_no" int,
  "post_sit_no" char(13),
  "sit_name" nvarchar(60),
  "post_stat" int,
  "ar_no" float,
  "stat" nvarchar(30),
  "typ" nvarchar(30),
  "post_level_no" char(2),
  "LEVEL" nvarchar(20)
);

CREATE TABLE "view_site1" (
  "Expr1" char(10),
  "sit_name" nvarchar(60),
  "sit_no" char(10),
  "sit_nolevel" char(13),
  "sit_level" char(2),
  "sit_proccess" char(10),
  "sit_desc" nvarchar(100),
  "sit_doc_no" char(7),
  "sit_deb_dte" datetime,
  "sit_fin_dte" datetime,
  "sit_free" int,
  "sit_typ" char(2),
  "sit_intkb" int,
  "sit_morch" int,
  "sit_wly_no" int,
  "sit_stat" char(2),
  "sit_user" char(3),
  "sit_permition" int,
  "sit_leve" char(1),
  "sit_kind" char(2)
);

CREATE TABLE "view_siteform" (
  "sit_no" char(10),
  "SUB_NAME" nvarchar(60),
  "sub_cod" nvarchar(10),
  "sit_nolevel" char(13),
  "sit_level" char(2),
  "sit_wly_no" int,
  "sit_leve" char(1),
  "sit_permition" int,
  "sit_user" char(3),
  "SUB_NAME_PRINT" nvarchar(100),
  "sit_stat" char(2),
  "sit_free" int
);

COMMENT ON COLUMN "ANALIS"."AUTO" IS 'Identity PK';

ALTER TABLE "main" ADD FOREIGN KEY ("MN_APP_NO") REFERENCES "ARTICLE" ("ART_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main" ADD FOREIGN KEY ("MN_APP_NO") REFERENCES "BOOK" ("BK_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RES" ADD FOREIGN KEY ("RES_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RES" ADD FOREIGN KEY ("RES_RES_NO") REFERENCES "AUTHER" ("AUT_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ISTARA" ADD FOREIGN KEY ("iar_book") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ISTARA" ADD FOREIGN KEY ("IAR_PRS") REFERENCES "PERSON" ("PRS_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ISTARA" ADD FOREIGN KEY ("iar_book") REFERENCES "BOOK" ("BK_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ARTICLE" ADD FOREIGN KEY ("ART_PER_NO") REFERENCES "PERIOD" ("PER_PER_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TRANS" ADD FOREIGN KEY ("TRS_NO") REFERENCES "PERIOD" ("PER_PER_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DIGIT" ADD FOREIGN KEY ("DIG_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ANALIS" ADD FOREIGN KEY ("AN_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ANALIS" ADD FOREIGN KEY ("AN_DESC_NO") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "NAROWER" ADD FOREIGN KEY ("NAR_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "NAROWER" ADD FOREIGN KEY ("NAR_NAR_NO") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RELATIVE" ADD FOREIGN KEY ("REL_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RELATIVE" ADD FOREIGN KEY ("REL_REL_NO") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GEO" ADD FOREIGN KEY ("GEO_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FILE_ADD" ADD FOREIGN KEY ("FAD_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEXT" ADD FOREIGN KEY ("TXT_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OPR_CHRT" ADD FOREIGN KEY ("OPR_NO1") REFERENCES "CHARIT" ("CHA_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SUBJECT" ADD FOREIGN KEY ("SUB_FORM") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SUBJECT" ADD FOREIGN KEY ("SUB_MCNZ") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REL_FORM" ADD FOREIGN KEY ("RLF_FORM1") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REL_FORM" ADD FOREIGN KEY ("RLF_FORM2") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REL_FORM" ADD FOREIGN KEY ("RLF_FORM1") REFERENCES "POSITION" ("POS_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_bnkout" ADD FOREIGN KEY ("user_out_num") REFERENCES "bnkout" ("OUT_NUM") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "catogorie" ADD FOREIGN KEY ("cat_num") REFERENCES "bnkout" ("OUT_NUM") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "demand" ADD FOREIGN KEY ("dmd_mch_no") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "demand" ADD FOREIGN KEY ("dmd_user") REFERENCES "config" ("user_no") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("post_no") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sites" ADD FOREIGN KEY ("sit_no") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "IST_BK" ADD FOREIGN KEY ("IAB_NO") REFERENCES "ISTARA" ("IAR_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "IST_BK" ADD FOREIGN KEY ("IAB_BOOK") REFERENCES "BOOK" ("BK_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "BOOK" ADD FOREIGN KEY ("BK_PBLSHR") REFERENCES "AUTHER" ("AUT_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SERIES" ADD FOREIGN KEY ("SER_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "date_subject" ADD FOREIGN KEY ("dte_app_no") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "text1" ADD FOREIGN KEY ("txt_no") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "result" ADD FOREIGN KEY ("res_dig_no") REFERENCES "DIGIT" ("DIG_DIG_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tmp_fileadd" ADD FOREIGN KEY ("tmp_user_no") REFERENCES "config" ("user_no") DEFERRABLE INITIALLY IMMEDIATE;
