CREATE TABLE "ANALIS" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AN_APP_NO" varchar(7),
  "AN_DESC_NO" varchar(9),
  "AN_SER_NO" varchar(2)
);

CREATE TABLE "ARRAYS" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" varchar(20),
  "AR_LEVEL" varchar(1)
);

CREATE TABLE "ARRAYS1" (
  "ar_typ" varchar(2),
  "ar_no" float,
  "ar_desc" varchar(30)
);

CREATE TABLE "ARTICLE" (
  "ART_APP_NO" varchar(7) PRIMARY KEY,
  "ART_YEAR" float,
  "ART_VOL" float,
  "ART_NO" int,
  "ART_DTE" timestamp,
  "ART_PER_NO" float,
  "ART_SUB_TY" varchar(2),
  "ART_PG_NO" varchar(5),
  "ART_CO_NO" varchar(3),
  "ART_SER_NO" float,
  "ART_FLM_NO" float,
  "ART_TYP" float,
  "ART_LANG" varchar(1),
  "ART_DTE1" timestamp,
  "ART_PER1" float,
  "ART_CHOICE" float,
  "art_upd" float,
  "ART_PIC" char(6),
  "ART_LANG1" char(2)
);

CREATE TABLE "AUTHER" (
  "AUT_TYP" varchar(2),
  "AUT_NO" float,
  "AUT_NAM" varchar(100),
  "aut_sub_no" char(10)
);

CREATE TABLE "BOOK" (
  "BK_APP_NO" varchar(7),
  "BK_PUB_LOC" varchar(8),
  "BK_PBLSHR" float,
  "BK_PUB_TYP" varchar(2),
  "BK_SLCT_NO" varchar(20),
  "BK_PUB_DTE" timestamp,
  "BK_MAT_CNT" varchar(10),
  "BK_LANG3" varchar(1),
  "BK_EDTN" float,
  "BK_RDMK" varchar(15),
  "BK_CVR" varchar(2),
  "BK_PG_NO" float,
  "BK_PRT_NO" float,
  "BK_IS_SER" boolean NOT NULL,
  "BK_NO_CP" float,
  "BK_REG_NO" float,
  "BK_ADT_TTL" varchar(75),
  "BK_KHALIF" varchar(35),
  "BK_VOL" float,
  "BK_WATH_TY" varchar(2),
  "BK_QUATER" varchar(11),
  "BK_SAVE" float,
  "BK_PRIX" float,
  "BK_IKTDTE" timestamp,
  "BK_MTRJM" float,
  "BK_SER_TTL" varchar(60),
  "BK_SER_NO" float,
  "BK_LANG1" varchar(1),
  "bk_vol1" float,
  "bk_mjld" float,
  "bk_mjld1" float,
  "bk_jz" float,
  "bk_jz1" float,
  "bk_content" varchar(130),
  "bk_memo" varchar(200),
  "bk_year_pub" float,
  "bk_typ_year" float,
  "bk_result" varchar(1000),
  "bk_free" float,
  "bk_lang" varchar(1),
  "bk_iar_no" varchar(6),
  "bk_stat" char(2)
);

CREATE TABLE "CHARIT" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CHA_NO" varchar(6),
  "CHA_SUB" varchar(2),
  "CHA_TYP" float,
  "CHA_TIME" float,
  "CHA_DTE" timestamp,
  "CHA_NUM" float,
  "CHA_TYP1" float,
  "CHA_SOURCE" varchar(3),
  "CHA_DTE1" timestamp,
  "CHA_TITLE" varchar(70),
  "CHA_STOCK" float,
  "CHA_NBDIS" float,
  "CHA_SUBJCT" varchar(3),
  "CHA_FRM" varchar(3),
  "cha_to" varchar(3),
  "cha_prsfrm" varchar(3),
  "cha_prsto" varchar(3),
  "cha_opr_no" varchar(7),
  "cha_tmcode" varchar(2)
);

CREATE TABLE "CODING" (
  "SUB_LEVE" varchar(1),
  "SUB_CODE" varchar(4),
  "SUB_DESC" varchar(100)
);

CREATE TABLE "COTE_PUB" (
  "CTP_NO" float,
  "CTP_NAM" varchar(40)
);

CREATE TABLE "DICT" (
  "SUB_CODE3" varchar(9),
  "NUM" float,
  "SUB_DESC3" varchar(30)
);

CREATE TABLE "DIGIT" (
  "DIG_NO" char(7) NOT NULL,
  "DIG_DIG_NO" char(6),
  "DIG_TYP" char(4),
  "DIG_SER" int NOT NULL,
  "DIG_TYP1" char(2),
  "DIG_O" int,
  "DIG_M" int,
  "DIG_S" int,
  "DIG_O1" int,
  "DIG_M1" int,
  "DIG_S1" int,
  "DIG_SIZE" decimal(5,2),
  "DIG_NOCHRT" char(6),
  "dig_newnochrt" char(6),
  "dig_typchrt" char(2),
  "dig_geochrt" char(10),
  "dig_choice" int,
  "dig_nochrt1" char(8),
  "dig_typmat" char(2),
  "dig_typ_high" char(3),
  PRIMARY KEY ("DIG_NO", "DIG_SER")
);

CREATE TABLE "FILE_ADD" (
  "FAD_APP_NO" varchar(7),
  "FAD_DESC_N" varchar(9),
  "FAD_SER_NO" varchar(2),
  "FAD_FAD_T1" varchar(1),
  "FAD_FAD_T2" varchar(1),
  "FAD_RLTV_N" varchar(2),
  "FAD_FAD_NO" varchar(10)
);

CREATE TABLE "FILE_ADD2" (
  "FAD_APP_NO" varchar(7),
  "FAD_DESC_N" varchar(9),
  "FAD_SER_NO" varchar(2),
  "FAD_FAD_T1" varchar(1),
  "FAD_FAD_T2" varchar(1),
  "FAD_RLTV_N" varchar(2),
  "FAD_FAD_NO" varchar(10)
);

CREATE TABLE "GEO" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "GEO_APP_NO" varchar(7),
  "GEO_DESC_N" varchar(9),
  "GEO_SER_NO" varchar(2),
  "GEO_GEO_NO" varchar(10)
);

CREATE TABLE "ISTARA" (
  "IAR_NO" varchar(6) NOT NULL,
  "IAR_DTE" timestamp,
  "IAR_PRS" varchar(5),
  "IAR_TYP" float,
  "IAR_CAUSE" varchar(2),
  "IAR_PERIOD" float,
  "IAR_DTE1" timestamp,
  "IAR_DTE2" timestamp,
  "IAR_RMK" varchar(70),
  "IAR_TYP1" float,
  "iar_book" varchar(7),
  "iar_serial" float NOT NULL,
  "iar_ent" varchar(3),
  "iar_ist_typ" float NOT NULL,
  "iar_reg_no" float,
  "iar_tamin" float,
  PRIMARY KEY ("IAR_NO", "iar_serial", "iar_ist_typ")
);

CREATE TABLE "IST_BK" (
  "IAB_NO" varchar(5),
  "IAB_SER" float,
  "IAB_BOOK" varchar(7)
);

CREATE TABLE "IST_OTH" (
  "IAO_NO" varchar(5),
  "IAO_SER" float,
  "IAO_TIT" varchar(60),
  "IAO_TYP" float,
  "IAO_NB" float
);

CREATE TABLE "MACNZ" (
  "SUB_CODE" varchar(9),
  "SUB_LEVEL" varchar(1),
  "SUB_DESC" varchar(40),
  "SUB_LOGIC" float
);

CREATE TABLE "MEM" (
  "SUB_CODE4" varchar(9),
  "NUMBER" float,
  "SUB_DESC4" varchar(30)
);

CREATE TABLE "NAROWER" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NAR_APP_NO" varchar(7),
  "NAR_DESC_N" varchar(9),
  "NAR_SER_NO" varchar(2),
  "NAR_RLTV_N" varchar(2),
  "NAR_NAR_TY" varchar(1),
  "NAR_NAR_NO" varchar(9)
);

CREATE TABLE "NEWS" (
  "NEWS_NO" varchar(7),
  "NEWS_DOC" varchar(2),
  "NEWS_DTE_D" timestamp,
  "NEWS_DTE" timestamp,
  "NEWS_NUM" float,
  "NEWS_TIT1" varchar(75),
  "NEWS_TIT2" varchar(75),
  "NEWS_DES_T" varchar(2),
  "NEWS_DES_D" timestamp,
  "NEWS_DES_P" float,
  "NEWS_PUB" float,
  "NEWS_DES_N" varchar(9),
  "NEWS_MLH" float
);

CREATE TABLE "NEWS_WRD" (
  "WRD_APP_NO" varchar(7),
  "WRD_WORD" varchar(12)
);

CREATE TABLE "OPR_CHRT" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OPR_NO" varchar(7),
  "OPR_SER" float,
  "OPR_NO1" varchar(6),
  "OPR_SUB" varchar(2),
  "OPR_DTE" timestamp,
  "OPR_TIME" varchar(15),
  "OPR_COTFRM" varchar(3),
  "OPR_PRSFRM" varchar(3),
  "OPR_COTTO" varchar(3),
  "OPR_PRSTO" varchar(3),
  "OPR_DTE1" timestamp,
  "OPR_RMK" varchar(50),
  "OPR_TITLE" varchar(70),
  "OPR_TRANS" boolean NOT NULL,
  "opr_choice" char(20),
  "opr_extcote" char(10)
);

CREATE TABLE "PERIOD" (
  "PER_PER_NO" float,
  "PER_PER_NA" varchar(40),
  "PER_PUB_LO" float,
  "PER_ST_DTE" timestamp,
  "PER_LANG" varchar(1),
  "PER_RDMD" varchar(15),
  "PER_TYP" float,
  "PER_GEO" varchar(10),
  "PER_TYP1" varchar(2),
  "PER_FREQ" varchar(2),
  "PER_ADRS" varchar(65),
  "PER_TEL" varchar(16),
  "PER_AMNT" float,
  "PER_PRIX" float,
  "PER_PBLSHR" float,
  "PER_PRIX1" float,
  "PER_PUB" varchar(10),
  "PER_MOASS" varchar(10),
  "PER_TAHRIR" varchar(10),
  "PER_DIRCT" varchar(10),
  "PER_PRESD" varchar(10),
  "PER_UTILS" float,
  "PER_GEO1" varchar(10),
  "PER_TAH1" varchar(10),
  "PER_FAX" varchar(15),
  "PER_CREAT" varchar(10),
  "PER_DTE" timestamp,
  "per_email" varchar(60),
  "per_website" varchar(60)
);

CREATE TABLE "PERSON" (
  "PRS_NO" char(10),
  "PRS_NAME" varchar(50),
  "PRS_INST" varchar(10),
  "PRS_ADRS" varchar(100),
  "prs_inst_tel" varchar(30),
  "PRS_INST_BOX" varchar(15),
  "PRS_INST_DIRCT" varchar(50),
  "PRS_INST_EMAIL" varchar(50),
  "PRS_KAYD" varchar(10),
  "PRS_BRTH_DTE" timestamp,
  "PRS_VLG" varchar(10),
  "PRS_SAKAN" varchar(10),
  "PRS_ADRS1" varchar(100),
  "PRS_TEL" varchar(50),
  "PRS_EMAIL" varchar(50),
  "PRS_BOX" varchar(50),
  "prs_qualty" varchar(3),
  "prs_icht_dte1" timestamp,
  "prs_ent" char(2),
  "prs_mzhb" char(3),
  "prs_politc" char(3),
  "prs_social_media" char(100),
  "prs_oldjob" char(3),
  "prs_sex" char(3)
);

CREATE TABLE "PERSON1" (
  "PRS_NO" varchar(5),
  "PRS_NAME" varchar(25),
  "PRS_INST" varchar(10),
  "PRS_ADRS" varchar(40),
  "prs_inst_tel" varchar(30),
  "PRS_INST_BOX" varchar(15),
  "PRS_INST_DIRCT" varchar(10),
  "PRS_INST_EMAIL" varchar(30),
  "PRS_KAYD" varchar(10),
  "PRS_BRTH_DTE" timestamp,
  "PRS_VLG" varchar(10),
  "PRS_SAKAN" varchar(10),
  "PRS_ADRS1" varchar(50),
  "PRS_TEL" varchar(20),
  "PRS_EMAIL" varchar(30),
  "PRS_BOX" varchar(15),
  "PRS_TYP_ICHT" int,
  "prs_qualty" varchar(4),
  "prs_icht_dte1" timestamp,
  "prs_icht_dte2" timestamp,
  "prs_ent" char(2)
);

CREATE TABLE "PICTURE" (
  "pic_no" varchar(7),
  "pic_ng_no" varchar(6),
  "pic_pos_no" varchar(6),
  "pic_doc" varchar(3),
  "pic_doc_dte" timestamp,
  "pic_ent" varchar(3),
  "pic_ent_dte" timestamp,
  "pic_prs" varchar(3),
  "pic_dte" timestamp,
  "pic_tit" varchar(100),
  "pic_cot" varchar(10),
  "pic_geo" varchar(10),
  "pic_typ" float,
  "pic_form" float,
  "pic_len" float,
  "pic_large" float,
  "pic_qualty" float,
  "pic_sub" float,
  "pic_rmrk" varchar(70),
  "pic_copy" float,
  "pic_lbn" varchar(5),
  "pic_page" varchar(5),
  "pic_line" varchar(5),
  "pic_typ1" float,
  "pic_brind" float,
  "pic_choice" float
);

CREATE TABLE "POSITION" (
  "POS_NO" varchar(10),
  "POS_NAM" varchar(80),
  "DAT_REC" timestamp
);

CREATE TABLE "POUT" (
  "auto" int PRIMARY KEY,
  "OUT_IST" varchar(2),
  "OUT_NUM" float,
  "OUT_DESC" varchar(25),
  "OUT_NAME" varchar(20),
  "OUT_FIELD" varchar(20),
  "OUT_SCOND0" varchar(70),
  "OUT_SCOND" varchar(70),
  "OUT_SCOND1" varchar(120),
  "OUT_MCOND" varchar(45),
  "OUT_MCOND1" varchar(45),
  "out_ext" varchar(5),
  "OUT_LEN" float,
  "OUT_LEN1" float,
  "OUT_COND" varchar(80),
  "OUT_SELECT" varchar(20),
  "OUT_INDX" float,
  "OUT_INDX3" float,
  "OUT_SEK" varchar(1),
  "OUT_IF" varchar(1),
  "OUT_CHIOCE" float,
  "OUT_NATURE" varchar(1),
  "OUT_SLCT1" varchar(20),
  "OUT_INDX1" varchar(20),
  "OUT_COD" varchar(60),
  "OUT_VCOD" varchar(2),
  "OUT_NAMCOD" varchar(35),
  "OUT_NAMCOD1" varchar(12),
  "OUT_FINDX" varchar(1),
  "OUT_RCRN" varchar(1),
  "OUT_INDX12" float,
  "OUT_COND1" varchar(40),
  "OUT_TYP" varchar(1),
  "OUT_REL" varchar(20),
  "OUT_CHIO1" float,
  "out_rel1" varchar(12),
  "out_rel2" varchar(12),
  "out_rel3" varchar(12)
);

CREATE TABLE "POUT1" (
  "OUT_IST" varchar(2),
  "OUT_NUM" float,
  "OUT_DESC" varchar(25),
  "OUT_NAME" varchar(12),
  "OUT_FIELD" varchar(100),
  "OUT_SCOND0" varchar(100),
  "OUT_SCOND" varchar(200),
  "OUT_SCOND1" varchar(200),
  "OUT_MCOND" varchar(100),
  "OUT_MCOND1" varchar(100),
  "OUT_LEN" float,
  "OUT_LEN1" float,
  "OUT_COND" varchar(40),
  "OUT_SELECT" varchar(53),
  "OUT_INDX" float,
  "OUT_INDX3" float,
  "OUT_SEK" varchar(1),
  "OUT_IF" varchar(1),
  "OUT_CHIOCE" float,
  "OUT_NATURE" varchar(1),
  "OUT_SLCT1" varchar(53),
  "OUT_INDX1" varchar(53),
  "OUT_COD" varchar(80),
  "OUT_VCOD" varchar(2),
  "OUT_NAMCOD" varchar(50),
  "OUT_NAMCOD1" varchar(50),
  "OUT_RCRN" varchar(1),
  "OUT_INDX12" float,
  "OUT_COND1" varchar(50),
  "OUT_TYP" varchar(1),
  "OUT_REL" varchar(20),
  "OUT_CHIO1" float,
  "out_serial" float,
  "OUT_REL1" varchar(12),
  "OUT_REL2" varchar(12),
  "OUT_REL3" varchar(12)
);

CREATE TABLE "RELATIVE" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "REL_APP_NO" varchar(7),
  "REL_DESC_N" varchar(9),
  "REL_SER_NO" varchar(2),
  "REL_RLTV_N" varchar(2),
  "REL_RLTV_T" varchar(1),
  "REL_REL_NO" varchar(9)
);

CREATE TABLE "RELIS" (
  "SUB_CODE1" varchar(9),
  "SUB_CODE2" varchar(9),
  "RELITION" float
);

CREATE TABLE "REL_FORM" (
  "RLF_FORM1" varchar(10),
  "RLF_FORM2" varchar(10),
  "RLF_DTE" timestamp,
  "RLF_DTE1" timestamp,
  "RLF_REL" varchar(2)
);

CREATE TABLE "RES" (
  "AUTO" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RES_APP_NO" varchar(7),
  "RES_APP_TY" varchar(2),
  "RES_RES_NO" float
);

CREATE TABLE "SERIES" (
  "SER_APP_NO" varchar(7),
  "SER_AC_TTL" varchar(40),
  "SER_AD_TTL" varchar(40),
  "SER_ACT_NO" float,
  "SER_ADD_NO" float
);

CREATE TABLE "SUBJECT" (
  "SUB_FORM" varchar(10),
  "SUB_MCNZ" varchar(9),
  "SUB_DTE" timestamp,
  "SUB_DTE1" timestamp,
  "SUB_REL" varchar(2)
);

CREATE TABLE "TEMP" (
  "FIELD_NAME" varchar(10),
  "FIELD_TYPE" varchar(1),
  "FIELD_LEN" float,
  "FIELD_DEC" float
);

CREATE TABLE "TEXT" (
  "TXT_APP_NO" varchar(7),
  "TXT_MEM" varchar(70),
  "txt_ser" float,
  "txt_page" float
);

CREATE TABLE "TIME" (
  "TM_APP_NO" varchar(7),
  "TM_DESC_NO" varchar(9),
  "TM_SER_NO" varchar(2),
  "TM_RLTV_NO" varchar(2),
  "TM_O" float,
  "TM_M" float,
  "TM_S" float,
  "TM_O1" float,
  "TM_M1" float,
  "TM_S1" float
);

CREATE TABLE "TRANS" (
  "TRS_OPNO" float,
  "TRS_NO" float,
  "TRS_DTE" timestamp,
  "TRS_NUM" varchar(5),
  "TRS_NB" float,
  "TRS_YEAR" float,
  "TRS_TYP" float,
  "TRS_DTE1" timestamp
);

CREATE TABLE "WORD" (
  "SUB_CODE6" varchar(10),
  "SUB_DESC6" varchar(12),
  "SUB_TYP6" varchar(1)
);

CREATE TABLE "abb" (
  "REL_APP_NO" varchar(7),
  "REL_DESC_N" varchar(9),
  "REL_SER_NO" varchar(2),
  "REL_RLTV_N" varchar(2),
  "REL_RLTV_T" varchar(1),
  "REL_REL_NO" varchar(9)
);

CREATE TABLE "abbas" (
  "id1" decimal(18,0)
);

CREATE TABLE "bnkout" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OUT_NUM" float,
  "OUT_DESC" varchar(40),
  "OUT_NAME" varchar(20),
  "OUT_FIELD" varchar(20),
  "OUT_SCOND0" varchar(70),
  "OUT_SCOND" varchar(70),
  "OUT_SCOND1" varchar(160),
  "OUT_MCOND" varchar(45),
  "OUT_MCOND1" varchar(30),
  "out_ext" varchar(5),
  "OUT_LEN" float,
  "OUT_LEN1" float,
  "OUT_COND" varchar(60),
  "OUT_DISPLAY" varchar(80),
  "OUT_SELECT" varchar(15),
  "out_fldselect" varchar(20),
  "OUT_INDX" varchar(15),
  "OUT_INDX3" varchar(15),
  "OUT_SEK" varchar(1),
  "OUT_IF" varchar(1),
  "OUT_CHIOCE" float,
  "OUT_NATURE" varchar(1),
  "OUT_SLCT1" varchar(15),
  "OUT_INDX1" varchar(15),
  "OUT_COD" varchar(60),
  "OUT_VCOD" varchar(2),
  "OUT_NAMCOD" varchar(35),
  "OUT_namcod1" varchar(15),
  "OUT_RCRN" varchar(1),
  "OUT_INDX12" float,
  "OUT_COND1" varchar(35),
  "OUT_TYP" varchar(1),
  "OUT_REL" varchar(12),
  "OUT_REL1" varchar(12),
  "OUT_REL2" varchar(12),
  "OUT_REL3" varchar(30),
  "OUT_T2" varchar(30),
  "OUT_CHIO1" float,
  "OUT_SCOND2" varchar(40),
  "OUT_MCOND2" varchar(40),
  "OUT_FIELD2" varchar(25),
  "OUT_SLCT2" float,
  "OUT_INDX2" float,
  "OUT_CAT" char(2)
);

CREATE TABLE "catogorie" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cat_no" char(2),
  "cat_num" int
);

CREATE TABLE "config" (
  "user_no" char(3),
  "user_name" char(50),
  "user_password" char(15),
  "user_cnf_path" char(100),
  "user_start" int,
  "USER_PWD" int,
  "user_cmpvd" char(100),
  "user_video_path" char(100),
  "user_company" int,
  "user_video_path1" char(100),
  "SITE_WLY" int,
  "user_level" char(1),
  "user_permition" int,
  "user_ent" char(2),
  "user_doc" char(2)
);

CREATE TABLE "date_subject" (
  "dte_app_no" char(7),
  "dte_ser_no" char(2),
  "dte_rel_no" char(2),
  "dte_desc_no" char(9),
  "dte_dte_deb" timestamp,
  "dte_dte_fin" timestamp
);

CREATE TABLE "demand" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dmd_no" char(7) NOT NULL,
  "dmd_ser" int NOT NULL,
  "dmd_user" char(3),
  "dmd_dte" timestamp,
  "dmd_in" decimal(18,0),
  "dmd_out" decimal(18,9),
  "dmd_path" char(100),
  "dmd_time" decimal(18,0),
  "dmd_mch_no" char(7),
  "dmd_desc" char(100),
  "dmd_chek" int,
  "dmd_mch_stock" char(6),
  "dmd_s" int,
  "dmd_m" int,
  "dmd_o" int,
  "dmd_f" int,
  "dmd_cote" char(50),
  "dmd_time1" char(12),
  "dmd_chek1" boolean
);

CREATE TABLE "form" (
  "SUB_TYP" varchar(2),
  "SUB_NO" varchar(8),
  "SUB_NAME" varchar(60),
  "SUB_DTE" timestamp,
  "SUB_USER" char(3),
  "SUB_SEC" int,
  "SUB_NOJIHAD" int,
  "SUB_NAME_PRINT" char(100)
);

CREATE TABLE "form1" (
  "SUB_TYP" varchar(2),
  "SUB_NO" varchar(8),
  "SUB_NAME" varchar(80),
  "sub_dte" timestamp
);

CREATE TABLE "main" (
  "MN_APP_NO" char(7) PRIMARY KEY,
  "m_no1" varchar(7),
  "MN_ACT_TTL" varchar(125),
  "MN_ACT" varchar(50),
  "MN_ADD_TTL" varchar(125),
  "MN_ADD" varchar(50),
  "MN_DATA_EN" varchar(2),
  "MN_APP_DOC" varchar(2),
  "MN_ENT_DTE" timestamp,
  "MN_WRT_DTE" timestamp,
  "MN_APP_REV" varchar(2),
  "mn_no" char(10),
  "MN_RESULT" char(1000),
  "MN_TYP" char(1),
  "mn_trans" int DEFAULT 0
);

CREATE TABLE "main2" (
  "MN_APP_NO" varchar(7),
  "MN_ACT_TTL" varchar(125),
  "MN_ACT" varchar(50),
  "MN_ADD_TTL" varchar(125),
  "MN_ADD" varchar(50),
  "MN_DATA_EN" varchar(2),
  "MN_APP_DOC" varchar(2),
  "MN_ENT_DTE" timestamp,
  "MN_WRT_DTE" timestamp,
  "MN_APP_REV" varchar(2),
  "MN_CHRT_NO" char(6),
  "MN_O" int,
  "MN_M" int,
  "MN_S" int,
  "MN_O1" int,
  "MN_M1" int,
  "MN_S1" int,
  "MN_SIZE" decimal(5,2),
  "MN_TYP" char(1),
  "MN_PIC" char(2),
  "MN_VOI" char(2),
  "MN_RESULT" varchar(500)
);

CREATE TABLE "posts" (
  "post_serial" char(6) PRIMARY KEY,
  "post_no" char(10),
  "post_sit_no" char(13),
  "post_doc_no" char(7),
  "post_deb_dte" timestamp,
  "post_fin_dte" timestamp,
  "post_wly_no" int,
  "post_stat" int,
  "post_level_no" char(2),
  "post_typ" int,
  "post_user" char(3),
  "post_permition" int,
  "post_level" char(1)
);

CREATE TABLE "ranjpath" (
  "rjp_no" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rjp_nofrom" char(10),
  "rjp_noto" char(10),
  "rjp_path" char(200),
  "rjp_typ" int
);

CREATE TABLE "result" (
  "auto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "res_no" char(7) NOT NULL,
  "res_ser" int NOT NULL,
  "res_dig_no" char(6),
  "res_typ" char(3),
  "res_typ1" char(2),
  "res_dte" timestamp,
  "res_user_no" char(3),
  "res_no_ist" char(7),
  "res_prs" char(50),
  "res_cote" char(3),
  "res_permit" char(2),
  "res_subject" char(50)
);

CREATE TABLE "sites" (
  "sit_no" char(10),
  "sit_nolevel" char(13),
  "sit_level" char(2),
  "sit_proccess" char(10),
  "sit_desc" varchar(100),
  "sit_doc_no" char(7),
  "sit_deb_dte" timestamp,
  "sit_fin_dte" timestamp,
  "sit_free" int,
  "sit_typ" char(2),
  "sit_intkb" int,
  "sit_morch" int,
  "sit_wly_no" int,
  "sit_stat" char(2),
  "sit_user" char(3),
  "sit_permition" int,
  "sit_leve" char(1),
  "sit_kind" char(2),
  "sit_close_no" char(7)
);

CREATE TABLE "t_operation" (
  "F_DESC" varchar(4)
);

CREATE TABLE "text1" (
  "txt_no" varchar(7),
  "txt_desc_n" varchar(9),
  "txt_ser_no" varchar(2),
  "txt_rltv_n" varchar(2),
  "txt_rltv_typ" varchar(1),
  "txt_text" varchar(4000),
  "txt_nbpage" int
);

CREATE TABLE "tmp_fileadd" (
  "tmp_fad_no" varchar(7) NOT NULL,
  "tmp_ser" float,
  "tmp_file_name" varchar(50),
  "tmp_rmrk" varchar(50),
  "tmp_mk" varchar(30),
  "tmp_date" timestamp,
  "tmp_user_no" char(3),
  "tmp_final" int
);

CREATE TABLE "user_bnkout" (
  "user_ist_no" char(2) NOT NULL,
  "user_no" char(3) NOT NULL,
  "user_out_num" int NOT NULL,
  "user_out_choice" int,
  "user_index" char(3),
  "user_sing" char(1),
  "user_out_choi1" int,
  "user_sing1" char(1),
  PRIMARY KEY ("user_ist_no", "user_no", "user_out_num")
);

CREATE TABLE "view_array01" (
  "ar_typ" varchar(2),
  "ar_no" float,
  "ar_desc" varchar(30)
);

CREATE TABLE "view_array03" (
  "auto" int NOT NULL,
  "ar_typ" varchar(2),
  "ar_no" float,
  "ar_desc" varchar(30)
);

CREATE TABLE "view_array04" (
  "auto" int NOT NULL,
  "ar_typ" varchar(2),
  "ar_no" float,
  "ar_desc" varchar(30)
);

CREATE TABLE "view_array1" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" varchar(20),
  "AR_LEVEL" varchar(1)
);

CREATE TABLE "view_array2" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" varchar(20),
  "AR_LEVEL" varchar(1)
);

CREATE TABLE "view_arrays" (
  "AR_TYP" char(2),
  "AR_CODE" float,
  "AR_DESC" varchar(20),
  "AR_LEVEL" varchar(1)
);

CREATE TABLE "view_posts" (
  "post_no" char(10),
  "post_name" varchar(60),
  "post_doc_no" char(7),
  "post_deb_dte" timestamp,
  "post_fin_dte" timestamp,
  "post_wly_no" int,
  "post_sit_no" char(13),
  "sit_name" varchar(60),
  "post_stat" int,
  "ar_no" float,
  "stat" varchar(30),
  "typ" varchar(30),
  "post_level_no" char(2),
  "LEVEL" varchar(20)
);

CREATE TABLE "view_site1" (
  "Expr1" char(10),
  "sit_name" varchar(60),
  "sit_no" char(10),
  "sit_nolevel" char(13),
  "sit_level" char(2),
  "sit_proccess" char(10),
  "sit_desc" varchar(100),
  "sit_doc_no" char(7),
  "sit_deb_dte" timestamp,
  "sit_fin_dte" timestamp,
  "sit_free" int,
  "sit_typ" char(2),
  "sit_intkb" int,
  "sit_morch" int,
  "sit_wly_no" int,
  "sit_stat" char(2),
  "sit_user" char(3),
  "sit_permition" int,
  "sit_leve" char(1),
  "sit_kind" char(2)
);

CREATE TABLE "view_siteform" (
  "sit_no" char(10),
  "SUB_NAME" varchar(60),
  "sub_cod" varchar(10),
  "sit_nolevel" char(13),
  "sit_level" char(2),
  "sit_wly_no" int,
  "sit_leve" char(1),
  "sit_permition" int,
  "sit_user" char(3),
  "SUB_NAME_PRINT" varchar(100),
  "sit_stat" char(2),
  "sit_free" int
);

COMMENT ON COLUMN "ANALIS"."AUTO" IS 'Identity PK';

ALTER TABLE "BOOK" ADD CONSTRAINT "uq_book_app_no" UNIQUE ("BK_APP_NO");
ALTER TABLE "AUTHER" ADD CONSTRAINT "uq_auther_no" UNIQUE ("AUT_NO");
ALTER TABLE "PERIOD" ADD CONSTRAINT "uq_period_no" UNIQUE ("PER_PER_NO");
ALTER TABLE "MACNZ" ADD CONSTRAINT "uq_macnz_code" UNIQUE ("SUB_CODE");
ALTER TABLE "CHARIT" ADD CONSTRAINT "uq_charit_no" UNIQUE ("CHA_NO");
ALTER TABLE "form" ADD CONSTRAINT "uq_form_no" UNIQUE ("SUB_NO");
ALTER TABLE "POSITION" ADD CONSTRAINT "uq_position_no" UNIQUE ("POS_NO");
ALTER TABLE "bnkout" ADD CONSTRAINT "uq_bnkout_num" UNIQUE ("OUT_NUM");
ALTER TABLE "config" ADD CONSTRAINT "uq_config_user_no" UNIQUE ("user_no");
ALTER TABLE "PERSON" ADD CONSTRAINT "uq_person_no" UNIQUE ("PRS_NO");
ALTER TABLE "DIGIT" ADD CONSTRAINT "uq_digit_dig_no" UNIQUE ("DIG_DIG_NO");

ALTER TABLE "main" ADD FOREIGN KEY ("MN_APP_NO") REFERENCES "ARTICLE" ("ART_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main" ADD FOREIGN KEY ("MN_APP_NO") REFERENCES "BOOK" ("BK_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RES" ADD FOREIGN KEY ("RES_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RES" ADD FOREIGN KEY ("RES_RES_NO") REFERENCES "AUTHER" ("AUT_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ISTARA" ADD FOREIGN KEY ("iar_book") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ISTARA" ADD FOREIGN KEY ("IAR_PRS") REFERENCES "PERSON" ("PRS_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ISTARA" ADD FOREIGN KEY ("iar_book") REFERENCES "BOOK" ("BK_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ARTICLE" ADD FOREIGN KEY ("ART_PER_NO") REFERENCES "PERIOD" ("PER_PER_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TRANS" ADD FOREIGN KEY ("TRS_NO") REFERENCES "PERIOD" ("PER_PER_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DIGIT" ADD FOREIGN KEY ("DIG_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ANALIS" ADD FOREIGN KEY ("AN_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ANALIS" ADD FOREIGN KEY ("AN_DESC_NO") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "NAROWER" ADD FOREIGN KEY ("NAR_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "NAROWER" ADD FOREIGN KEY ("NAR_NAR_NO") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RELATIVE" ADD FOREIGN KEY ("REL_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RELATIVE" ADD FOREIGN KEY ("REL_REL_NO") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GEO" ADD FOREIGN KEY ("GEO_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FILE_ADD" ADD FOREIGN KEY ("FAD_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEXT" ADD FOREIGN KEY ("TXT_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OPR_CHRT" ADD FOREIGN KEY ("OPR_NO1") REFERENCES "CHARIT" ("CHA_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SUBJECT" ADD FOREIGN KEY ("SUB_FORM") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SUBJECT" ADD FOREIGN KEY ("SUB_MCNZ") REFERENCES "MACNZ" ("SUB_CODE") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REL_FORM" ADD FOREIGN KEY ("RLF_FORM1") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REL_FORM" ADD FOREIGN KEY ("RLF_FORM2") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REL_FORM" ADD FOREIGN KEY ("RLF_FORM1") REFERENCES "POSITION" ("POS_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_bnkout" ADD FOREIGN KEY ("user_out_num") REFERENCES "bnkout" ("OUT_NUM") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "catogorie" ADD FOREIGN KEY ("cat_num") REFERENCES "bnkout" ("OUT_NUM") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "demand" ADD FOREIGN KEY ("dmd_mch_no") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "demand" ADD FOREIGN KEY ("dmd_user") REFERENCES "config" ("user_no") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("post_no") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sites" ADD FOREIGN KEY ("sit_no") REFERENCES "form" ("SUB_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "IST_BK" ADD FOREIGN KEY ("IAB_BOOK") REFERENCES "BOOK" ("BK_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "BOOK" ADD FOREIGN KEY ("BK_PBLSHR") REFERENCES "AUTHER" ("AUT_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SERIES" ADD FOREIGN KEY ("SER_APP_NO") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "date_subject" ADD FOREIGN KEY ("dte_app_no") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "text1" ADD FOREIGN KEY ("txt_no") REFERENCES "main" ("MN_APP_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "result" ADD FOREIGN KEY ("res_dig_no") REFERENCES "DIGIT" ("DIG_DIG_NO") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tmp_fileadd" ADD FOREIGN KEY ("tmp_user_no") REFERENCES "config" ("user_no") DEFERRABLE INITIALLY IMMEDIATE;
