FROM eclipse-temurin:25-jdk
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg; rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]